### ISSUE TITLE
[SUGGESTION] Allow chocobos to spawn based on biomedict definitions for plains

### ISSUE THREAD

**Issue by Sunconure11** [Slayer5934/ChocoCraft3SLY#12]
https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/common/BiomeDictionary.java

This would allow them to be a bit more accessible in modpacks with biome-adding mods.

**Comment by SlayerTheChikken** [comment]
Ill definitely look into how to implement this.

**Comment by SlayerTheChikken** [comment]
Upon further inspection, it's already implemented! :P 
However, learning of this even existing is good, because I wanted to add more spawn-able places anyways.
Expect spawning in hills biomes to be added soon.
