### ISSUE TITLE
[0.9.6.0] Missing localization for creative tab

### ISSUE THREAD

**Issue by Lykrast** [Slayer5934/ChocoCraft3SLY#14]
![image](https://user-images.githubusercontent.com/8684850/43187281-4a28750c-8ff1-11e8-8f22-c2b1d7477cb6.png)

Self explanatory, missing a localization entry.

**Comment by SlayerTheChikken** [comment]
This will be fixed in 0.9.7.0, Ill close the issue when I'm done fixing it :)

**Comment by SlayerTheChikken** [comment]
Fixed in 0.9.7.0
