### ISSUE TITLE
Adjust saturation for food items.

### ISSUE THREAD

**Issue by Lykrast** [Slayer5934/ChocoCraft3SLY#15]
Food items replenish an excessive amount of saturation, as seen thanks to Apple Core here:
![image](https://user-images.githubusercontent.com/8684850/43187473-bf7085f2-8ff1-11e8-9c0e-1fc8cb9dafa9.png)
![image](https://user-images.githubusercontent.com/8684850/43187488-c749be1a-8ff1-11e8-9995-c450793edd62.png)
![image](https://user-images.githubusercontent.com/8684850/43187493-cbe59d2c-8ff1-11e8-8f7a-70fb14215fa5.png)

They should be tuned down to be more in line with vanilla food. You can see their saturation values when they are created in the Item class.

Beef for reference:
![image](https://user-images.githubusercontent.com/8684850/43187546-f60e6714-8ff1-11e8-89c6-ac876446c887.png)

**Comment by SlayerTheChikken** [comment]
This will ALSO be fixed in 0.9.7.0, Ill close this issue as well when I'm done fixing it

**Comment by SlayerTheChikken** [comment]
Fixed in Version 0.9.7
