### ISSUE TITLE
Implement new stat calc and config values.

### ISSUE THREAD

**Issue by Valentinez** [Slayer5934/ChocoCraft3SLY#16]
Now I know this mod has been redone several times, so things are bound to change. 
However, we need an updated Wiki. 
Crafting guides and all that. 

I haven't played since 1.7.10... so yeah.

Used to be able to get a Chocopedia by right clicking with a writable book [Book and Quill yes?]
This is not working anymore [not sure if intended...]

Also used to be able to obtain Chocobo feathers by Chocobos dropping them, or killing them. 
Used to be able to configure drop rates to in Config as well.

They drop the meat upon death, but do no drop feathers, killed or otherwise.

Mods I'm Using:
The Twilight Forest
Tinkers' Construct
Chococraft 3
JourneyMap
Improved Backpacks
Biomes O' Plenty
Mantle

Forge: 1.12.2-14.23.4.2705

**Comment by EvaShark** [comment]
Chocopedia is currently crafted using a book and a Gysahl Green in any crafting menu, and as far as I can tell, chocobo feathers haven't been implemented yet. I highly recommend the Just Enough Items mod to check on item recipes for modded content.

**Comment by Valentinez** [comment]
Ah, ok. Will use that mod for sure!
Gonna figure out how to make a nest and saddle... been just spawning them in.

I'd be more than happy to create a wiki for this thing.
Crafting guides, mechanics and all that. 

Cause also, I noticed they only follow if you have gysahl greens in hand.
Is there a way to toggle stay/follow/wander?

I noticed once my chocobo learned the fly ability, after a bit, dismounting on an island, my chocobo flew off into the sky by itself...

Wish I was better at programming, I'd be working on this everyday... 
I have alot of ideas, but not the programming skill to make it happen, or even if some things are possible. Like adding the breeding/stat algorithm for baby chicobos to the config file so it can be edited by the user. 

Also, if there could be like a min-max range for wild chocobo stats, that would be awesome. Cause when I set the stats in config, they all spawn the same, would be awesome to have a variance. Again could be something already in the works for that, I don't know.

**Comment by SlayerTheChikken** [comment]
I dont have enough time to make a wiki, unfortunately. So if anyone wants to step in and do that itd be nice :P 

But anyways, following/stay/wander is being worked on and will be done soon, this will be done through a chocobo whistle.

There's a glitch when if you log off while mounting and log back in the chocobo will still follow your movement. This has already been submitted by myself as an issue.

The breeding values are changeable in the config already.

Maybe one day I can implement random wild stats.

**Comment by Valentinez** [comment]
Well, I see max values for the breeding config, not too sure what that does...

I meant more like editing how the end result of stats are determined.
Like let's say this is the breeding formula:  

[Lets just do Health]
`health = (parent1health + parent2health / random(hpMin, hpMax)) + random(var1, var2);`

Config:
```
breeding {
//1.8-2.1 recommended,
//1= double Health, 2 = Average of Parent Health
   hpMin = 1.1
   hpMax = 1.9
//variance of total for more random results
   var1 = 10
   var2 = -10
```
In this way, I can set it so that they never go below the average of the stats of the parent, and also has a chance to be just about double stats of parent, this keeps it random, but user controllable.

For chocobo stats:
```
chocobo_health_wild = random(whpMin, whpMax);
chocobo_speed_wild = random(wspMin, wspMax);
chocobo_stamina_wild = random(wstmMin, wstmMax);

```
Config:
```
chocobo {
//Wild Chocobo Health Variance
whpMin = 10
whpMax = 50

//Wild Chocobo Speed Variance
wspMin = 5
wspMax = 30

//Wild Chocobo Stamina Variance
wstmMin = 50
wstmMax = 150
```
So that can be user controlled too.

I have no idea how this kind of coding works, esp in relation to code and config files, so idk if it's possible, just putting the idea there.

**Comment by SlayerTheChikken** [comment]
Its definitely possible, and ill look into it soon.

**Comment by SlayerTheChikken** [comment]
Complete with commit 0a69b7aa1e71a25dc22fd4962fc58ba2e2d9fe30
