### ISSUE TITLE
Add chocobo feathers and maybe add the ability to use chocopedia for renaming.

### ISSUE THREAD

**Issue by MunLau24** [Slayer5934/ChocoCraft3SLY#17]
Hi!!
I'm new to the mod so sorry if this has already been explained. 

two questions,
my chocobos don't drop feathers... they aren't even in the mod I think.
2. How can I change the name of a chocobo?? I can't with the chocopedia-...

Thanks a lot!!!

**Comment by SlayerTheChikken** [comment]
You can probably use a name-tag, but I havnt tried honestly :P feathers arnt in yet.

**Comment by SlayerTheChikken** [comment]
Chocobo feathers are in Version 0.9.7, however name tags will stay the way of renaming chocobos.
