### ISSUE TITLE
Fix Chocobo WAA HEE WOOOOOO spam.

### ISSUE THREAD

**Issue by mallrat208** [Slayer5934/ChocoCraft3SLY#18]
Would it be possible to get a config option to change how often Chocobos 'speak'? They seem to do so continuously and it can get somewhat annoying. In the same vein it'd be useful to have a config option to individually tune their volume rather than all Friendly Creatures

**Comment by SlayerTheChikken** [comment]
I honestly don't even understand the sound system yet, but if all else fails I can edit the audio file to be a tad more "smooth"

**Comment by SlayerTheChikken** [comment]
Fixed in Version 0.9.7
