### ISSUE TITLE
Client crash on a server when spawning an entity/being close to an entity

### ISSUE THREAD

**Issue by nihiluis** [Slayer5934/ChocoCraft3SLY#26]
```
[10:53:44] [Netty Epoll Server IO #2/ERROR] [FML]: NetworkDispatcher exception
io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Die Verbindung wurde vom Kommunikationspartner zurückgesetzt
        at io.netty.channel.unix.FileDescriptor.readAddress(..)(Unknown Source) ~[FileDescriptor.class:?]
[10:53:44] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: Nihiluis lost connection: Internal Exception: io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Die Verbindung wurde vom Kommunikationspartner zurückgesetzt
```

when I spawn a chocobo with an egg on my server, I receive this error on the server and my client is put back to the multiplayer screen. i cant seem to find anything on the client in latest.log.

can I debug this further?

im using forge 2705 with spongeforge and a couple of my own mods.

**Comment by SlayerTheChikken** [comment]
I cant reproduce this error using chococraft eggs, I spawned every type of chocobo. I wont rule out the fact it could be chococraft, but ive seen this issue on a spongeforge server before (I did the test on a spongeforge server)... the debug log from the client would help me see whats up, most likely anyways..

**Comment by nihiluis** [comment]
Hmm, i'd say it's related then. It isn't simply the issue of spongeforge either since other custom entities dont have that issue and it somehow seems to be related to the client not just the server

Maybe someone else will chime in later and have some more info.. ill try to check the debug client log though. I think i already did that earlier and found nothing. Ill repeat

**Comment by Slayer5934** [comment]
@MairuFrost That crashlog is pointing to thaumcraft being the issue..

**Comment by SlayerTheChikken** [comment]
I'm going to go ahead and close this issue, it seems to be widely occurring and an issue even in default minecraft and many other mods. I have a feeling it boils down to some kind of nettyio issue when too many packets are involved, I'm not sure there much I could do to fix this issue..
If it comes up again here I may re-open this and continue research, but for now I have no idea.
