### ISSUE TITLE
Attacking Chocobo makes screen red

### ISSUE THREAD

**Issue by yd278** [Slayer5934/ChocoCraft3SLY#31]
It will turn back to normal after attack another entity.

**Comment by Slayer5934** [comment]
I have not observed this in a modpack with over a 100 mods, I also tried without other mods without this issue. Do you have any more relevant info that could help solve your issue? Maybe shaders used, optifine settings, anything that could contribute?

**Comment by SlayerTheChikken** [comment]
Accidentally closed it :P

**Comment by SlayerTheChikken** [comment]
Cancel that, I'm experiencing this issue now too, I'll try to see what's up.

**Comment by SlayerTheChikken** [comment]
Possibly relevant https://bugs.mojang.com/browse/MC-48954?jql=project%20%3D%20MC%20AND%20fixVersion%20%3D%20%22Minecraft%2014w18a%22

**Comment by SlayerTheChikken** [comment]
6e11c62
