### ISSUE TITLE
Crash with better hud

### ISSUE THREAD

**Issue by OwenLouis** [Slayer5934/ChocoCraft3SLY#32]
Game crashed when a new choco egg was born or placed.(crash-report attached)
[crash-2019-04-10_19.38.42-client.txt](https://github.com/Slayer5934/ChocoCraft3SLY/files/3063646/crash-2019-04-10_19.38.42-client.txt)

**Comment by mccreery** [comment]
[Better HUD](/mccreery/better-hud) author here. I've had a few duplicates of this crash with different mods, mostly NPEs like this one. I'm guessing `writeToNBT` isn't usually called on the client, so a good chunk of mods don't have a valid state on that side. Any insight on this?

**Comment by SlayerTheChikken** [comment]
This is the solution, it's fixed in the next version (hopefully, probably) :) Just inform each of the mod authors to do this same type of null check.  ab005fb23b156dcf2fa4b47fde6aef07c7a470d2

**Comment by SlayerTheChikken** [comment]
Could you check to see if its fixed with the latest chococraft update @mccreery or @OwenLouise

**Comment by OwenLouis** [comment]
@Slayer5934 It has already been fixed.Thanks a lot.:smile:
