### ISSUE TITLE
When the player gets on the boat after riding the chocobo, he can't come down.

### ISSUE THREAD

**Issue by Xinmudotmoe** [Slayer5934/ChocoCraft3SLY#33]
ModVersion: 0.9.8.0

Like This.

![F](https://user-images.githubusercontent.com/13375525/56887233-a6133180-6aa3-11e9-812a-75fee1ea54ab.gif)

The way to trigger is extremely simple.

![9](https://user-images.githubusercontent.com/13375525/56887241-b3302080-6aa3-11e9-8c1f-f417e1c7f1c1.gif)

Only if there is anything that can smash one of the boat, the chocobo, or the player.This strange state will be lifted.

**Comment by SlayerTheChikken** [comment]
I'll look into fixing this next version, thanks for the report!

**Comment by SlayerTheChikken** [comment]
@Xinmudotmoe I finally fixed this issue! :D
[fee624da0282573073872dfd8b9eae701e2eb916](https://github.com/Slayer5934/ChocoCraft3SLY/commit/fee624da0282573073872dfd8b9eae701e2eb916)
