### ISSUE TITLE
Suggestion: Add config for saddle pack.

### ISSUE THREAD

**Issue by joelou1** [Slayer5934/ChocoCraft3SLY#35]
Having a saddlebag allowing to move around and store items is neat on a chocobo. I love this feature. For balancing sake though, I would recommand adding the option to disable this functionality with the Saddle Pack. It adds a good amount of inventory, but the chocobo wearing it should act like a llama while wearing this. Also, according to the animation, there's no place for anyone to sit on. Adding a config that allows or disallow people to ride Saddle packed chocobo should be an option.

Any thoughts?

**Comment by SlayerTheChikken** [comment]
@joelou1 A little late but here you go. :)
https://github.com/Slayer5934/ChocoCraft3SLY/commit/aad4534ad810b19ddae278091108706b93561dfc
