### ISSUE TITLE
Just a Suggestion: Client Config for OG Chococraft Textures and Sounds?

### ISSUE THREAD

**Issue by River224** [Slayer5934/ChocoCraft3SLY#37]
I understand why you changed the sound in the recent versions, but it would still be nice to have access to the OG Chococraft feel. 

I don't expect this to be a high priority, but it would be appreciated if this was implemented someday.

Thank you for listening and keep up the good work!!^^

**Comment by SlayerTheChikken** [comment]
Wah Hee Woo
https://github.com/Slayer5934/ChocoCraft3SLY/commit/4d49c6ebf404ed113bf9d98b7a71b325246c07b2
