### ISSUE TITLE
Can't dismount chocobo after riding it 

### ISSUE THREAD

**Issue by Matemarthur** [Slayer5934/ChocoCraft3SLY#40]
Mounting and dismounting the chocobo was easy on a 1900MB RAM server, now I've upgraded to 6GB server and my chocobos are now buggy, I can't dismount them. 
Also getting the message of "moved to quickly"

**Comment by SlayerTheChikken** [comment]
You should always be able to dismount chocobos discounting when they are flying, I may have fixed the bug related to this already though. (I remember working on dismounting a while back..)
