### ISSUE TITLE
Can't dismount Chocobo

### ISSUE THREAD

**Issue by Matemarthur** [Slayer5934/ChocoCraft3SLY#41]
Mounting and dismounting the chocobo was easy on a 1900MB RAM server, now I've upgraded to 6GB server and my chocobos are now buggy, I can't dismount them. 
Also getting the message of "moved to quickly"

**Comment by bradsk88** [comment]
I ran into this today. I think maybe it was because I disconnected from the server _while riding the chocobo_?  When I reconnected, it's movement was strange. Once I dismounted, the chocobo seemed to move wherever I moved, but at a much faster speed.

**Comment by SlayerTheChikken** [comment]
@Matemarthur @bradsk88 If this happens again let me know, but leaving while riding a chocobo should dismount properly now.
