### ISSUE TITLE
[Crash] Possible spawn weight error

### ISSUE THREAD

**Issue by faeldray** [Slayer5934/ChocoCraft3SLY#44]
I'm running a server with a custom modpack I made, and one of my players will occasionally crash the server while exploring the nether.

https://pastebin.com/j596ZeHq

After searching for similar errors, it seems that it has to do with a bug in spawn weight. In this case, I think it's because I have the chocobo's spawn weight set to 0 (I have other methods for players to get chocobos). There hasn't been any issues with the overworld (which has been pre-generated mind you) but in the nether, I think that flame chocobos are attempting to spawn but can't because of the 0 spawn weight.

**Comment by SlayerTheChikken** [comment]
Fixed a billion years later, you are welcome c:
https://github.com/Slayer5934/ChocoCraft3SLY/commit/de84e3505527d469575d46e45e0ba0bac150932e
