### ISSUE TITLE
Suggestion: Not being able to hit your own chocobo whilst riding it.

### ISSUE THREAD

**Issue by A1suya** [Slayer5934/ChocoCraft3SLY#49]
As the title states.
I'm not saying it ought to be a warmount, but I would appreciate just being able to shoot a bow or break a flower without dismounting. Much like vanilla horses.
Thank you for making this mod.

**Comment by SlayerTheChikken** [comment]
Neither LivingDamageEvent nor LivingHurtEvent being canceled nor setEntityInvulnerable stopped the chocobos from being damaged, I also tried a bunch of other things but couldn't get anything to work. Really unless someone helps me with this one then it's not going to happen, doesn't really make sense why damage can't be canceled out. :/
