### ISSUE TITLE
Can't Damage/Kill/Hurt Chocobos

### ISSUE THREAD

**Issue by sainguinkrist** [Slayer5934/ChocoCraft3SLY#50]
All chocobos can't be damaged in any way unless in Creative Mode.

Found this issue when I added the mod to my modpack and server, it's replicable by itself with no other mods present.

We've also noticed that eggs are not hatching.

**Comment by SlayerTheChikken** [comment]
That sounds like the AI is broken... I will do some testing and work on it when possible..

**Comment by SlayerTheChikken** [comment]
Should be fixed now, open new issue if it is not..
