### ISSUE TITLE
Fix Chocobo mounting glitch for logging out/disconnecting.

### ISSUE THREAD

**Issue by SlayerTheChikken** [Slayer5934/ChocoCraft3SLY#6]
https://github.com/Xalcon/ChocoCraft3/issues/14

**Comment by SlayerTheChikken** [comment]
I researched the issue further, it always happens while logging out on a chocobo. Also, its going to be a pain to fix.

When the user logs out while riding the chocobo they do not dismount, this part is not the actual issue but Id still like that be part of the fix; The issue is when they log back in they are still riding but when they get off they can still control the chocobo with movement, this is bad.

**Comment by Slayer5934** [comment]
https://github.com/trashbyte Any ideas?

**Comment by SlayerTheChikken** [comment]
@trashbyte any ideas?

**Comment by mallrat208** [comment]
This should be an easy fix if you catch the player logged out event and just forcibly dismount them if they're on a chocobo.

**Comment by SlayerTheChikken** [comment]
After verifying the issue is resolved Ill go ahead and close this as fixed (: thank you
